@extends('templates.mainLayout')

@section('title')
    Homepage
@endsection

@section('content')
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sit amet metus mi. Duis at elementum ante, fringilla iaculis turpis. Pellentesque a arcu eget nisi rhoncus sodales. Integer placerat, velit at placerat viverra, dui libero porta elit, vehicula tempor neque erat a neque. Mauris arcu ligula, facilisis in dictum in, venenatis eget nunc. In dapibus rutrum felis, sit amet faucibus ex faucibus sed. In non odio dui. Morbi semper leo a turpis rutrum vestibulum. Donec eu metus quis nisi molestie porttitor non tempor neque. Nulla dictum neque at molestie malesuada. Ut semper, dolor consectetur suscipit pulvinar, massa magna tincidunt ex, sit amet tempor arcu lectus eget nisi. Phasellus facilisis neque massa, eget vestibulum lorem luctus ut.</p>
  <p>Phasellus ut interdum tellus. Nunc sit amet facilisis nisl, sed vehicula nunc. Fusce lorem metus, porttitor vel pellentesque vitae, ullamcorper non erat. Sed pretium laoreet tortor eu euismod. Sed consequat nibh ac consequat eleifend. Suspendisse potenti. Aliquam mollis massa eget blandit viverra. Ut elementum purus id vestibulum placerat. Etiam dapibus enim ut lacinia euismod. Morbi augue nibh, finibus porttitor dui ac, efficitur ullamcorper diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lobortis erat tempor justo imperdiet, in efficitur orci mattis. Duis dignissim hendrerit massa, eget pellentesque metus laoreet at. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus tempor quis lorem et vestibulum.</p>
  <p>Nam molestie libero quis facilisis facilisis. Sed congue lectus vel purus consequat dapibus. Vestibulum sem mauris, scelerisque vel consectetur ut, condimentum id mauris. Vestibulum et lacus ut risus ornare ultricies mattis id augue. Fusce dictum odio nibh. In hac habitasse platea dictumst. Curabitur porta dui interdum risus efficitur ornare. In faucibus, metus eu pellentesque sagittis, lorem justo convallis nunc, eu luctus sapien ligula non nunc. Curabitur nec porta ipsum. Sed eleifend sagittis ipsum. Donec ullamcorper accumsan metus ut aliquet. Aliquam aliquet, nisl a egestas posuere, orci nisi condimentum felis, vitae laoreet erat lacus nec nulla. Aenean ac mauris orci. Curabitur aliquet dui scelerisque quam congue, non aliquet elit tincidunt.</p>
@endsection
